# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2


orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run build
      - run: gradle build

      # store artifacts
      - run:
          command: |
            mkdir -p /tmp/generated_artifacts
            cp cli/build/libs/cli-jvm-executable-0.1.0.jar /tmp/generated_artifacts/shake.jar
            cp util/build/libs/ /tmp/generated_artifacts/util
            cp lexer/build/libs/ /tmp/generated_artifacts/lexer
            cp parser/build/libs/ /tmp/generated_artifacts/parser
            cp interpreter/build/libs/ /tmp/generated_artifacts/interpreter
            cp cli/build/libs/ /tmp/generated_artifacts/cli
          when: on_fail
      - store_artifacts:
          path: /tmp/generated_artifacts
