name: Dokka

on:
  push:
    branches: [ master ]

jobs:
  generate-dokka-docs:
    name: Generate Dokka Docs 📚
    runs-on: ubuntu-latest

    # We don't want to run this workflow on forks
    # We also don't want to run this workflow when the actor is our bot (shakelang-bot)
    if: github.repository_owner == 'shakelang' && github.actor != 'shakelang-bot'

    strategy:
      matrix:
        java-version: [ 16 ]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Setup Gradle 🛠️
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew 🔑
        run: chmod +x gradlew

      - name: Cache Gradle packages 📦
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle 🏗️
        run: ./gradlew dokkaHtmlMultiModule

      - name: Import GPG key 🗝️
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.ACTIONS_GPG_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Check Git Status 🔄
        working-directory: build/docs/
        run: git status

      - name: Commit Changes 📝
        working-directory: build/docs/
        run: |
          # Configure git
            git config --global user.name "shakebot[bot]"
            git config --global user.email "bot@shakelang.com"

          # Commit and push changes
            git add .
            git commit -m "Update documentation"

      - name: Push changes 🔀
        working-directory: build/docs/
        run: |
          # Push using the GITHUB_TOKEN
            git push https://shakelang-bot:${{ secrets.GH_BOT_TOKEN }}@github.com/shakelang/docs.git HEAD:master --force
