name: Format using ktlint

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on:
  push:
    branches: [master]
  schedule:
    - cron: "45 15 * * 4"

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Lint using ktlint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [16]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Lint with KtLint
        run: |
          ./gradlew ktlintFormat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Automated] Format using ktlint"
          title: "[Automated] Format using ktlint"
          body: "This is an automated pull request to format the code using ktlint."
          branch: ktlint-format-${{ github.sha }}
          branch-suffix: timestamp
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
